<center><h1 style="font-size:3em;color:#2467C0"> Generación de un dataframe de imagenes </h1></center>
 
    
    
## Objetivo:
    
    
En esta lección se mostrará como hacer una base de datos basado en imagenes.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2 as cv
from glob import glob

## Generación del dataframe de testeo

### Generación del dataframe "negativo"

In [21]:
count = 0
df_negative_test = pd.DataFrame()
for imagen in glob('datos/faces_test/negatives/*.jpg'):
    img = cv.imread(imagen)
    img_gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    img_r = cv.resize(img_gray, (40,40), interpolation = cv.INTER_NEAREST)
    fila = np.append(0, img_r.flatten())
    fila = fila.reshape(1, 1601  )
    df_negative_test = pd.concat([df_negative_test,  pd.DataFrame(fila)  ])
    count = count + 1
print(count)
df_negative_test

6

,0,1,2,3,4,5,6,7,8,9,...,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600
0,0,59,56,43,39,36,36,41,50,55,...,64,63,68,70,68,70,74,76,79,71
0,0,69,73,77,78,67,58,58,68,76,...,102,96,100,109,123,119,120,122,109,80
0,0,128,137,140,145,149,164,175,187,196,...,141,141,128,122,96,79,71,70,72,61
0,0,164,96,156,177,183,195,205,215,207,...,34,30,42,49,87,82,84,109,112,90
0,0,138,136,133,134,140,144,148,156,158,...,131,128,122,123,117,109,105,85,103,149
0,0,65,74,88,91,98,104,105,105,102,...,145,142,138,139,137,120,117,132,116,92

### Generación del dataframe "positivo"

In [22]:
count = 0
df_postive_test = pd.DataFrame()
for imagen in glob('datos/faces_test/positives/*.jpg'):
    img = cv.imread(imagen)
    img_gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    img_r = cv.resize(img_gray, (40,40), interpolation = cv.INTER_NEAREST)
    fila = np.append(1, img_r.flatten())
    fila = fila.reshape(1, 1601  )
    df_postive_test = pd.concat([df_postive_test,  pd.DataFrame(fila)  ])
    count = count + 1
print(count)
df_postive_test

6

,0,1,2,3,4,5,6,7,8,9,...,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600
0,1,30,32,31,35,48,160,176,189,193,...,139,138,136,136,133,130,128,123,119,113
0,1,42,55,57,63,78,98,106,125,132,...,179,177,170,167,157,141,136,129,125,118
0,1,106,111,106,111,108,106,112,106,110,...,134,129,118,116,109,103,104,110,116,130
0,1,138,136,133,134,140,144,148,156,158,...,131,128,122,123,117,109,105,85,103,149
0,1,146,144,139,143,149,154,154,156,162,...,124,120,84,64,39,39,39,41,40,40
0,1,138,143,149,146,147,144,140,138,150,...,134,117,102,101,72,92,135,207,209,227

### Unión de dataframes

Cración de un solo dataframe llamado df_faces

In [26]:
frames = [df_postive_test, df_negative_test]
df_faces_test = pd.concat(frames)
df_faces_test

,0,1,2,3,4,5,6,7,8,9,...,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600
0,1,30,32,31,35,48,160,176,189,193,...,139,138,136,136,133,130,128,123,119,113
0,1,42,55,57,63,78,98,106,125,132,...,179,177,170,167,157,141,136,129,125,118
0,1,106,111,106,111,108,106,112,106,110,...,134,129,118,116,109,103,104,110,116,130
0,1,138,136,133,134,140,144,148,156,158,...,131,128,122,123,117,109,105,85,103,149
0,1,146,144,139,143,149,154,154,156,162,...,124,120,84,64,39,39,39,41,40,40
0,1,138,143,149,146,147,144,140,138,150,...,134,117,102,101,72,92,135,207,209,227
0,0,59,56,43,39,36,36,41,50,55,...,64,63,68,70,68,70,74,76,79,71
0,0,69,73,77,78,67,58,58,68,76,...,102,96,100,109,123,119,120,122,109,80
0,0,128,137,140,145,149,164,175,187,196,...,141,141,128,122,96,79,71,70,72,61
0,0,164,96,156,177,183,195,205,215,207,...,34,30,42,49,87,82,84,109,112,90
0,0,138,136,133,134,140,144,148,156,158,...,131,128,122,123,117,109,105,85,103,149
0,0,65,74,88,91,98,104,105,105,102,...,145,142,138,139,137,120,117,132,116,92

Se realiza un shuffle en los datos

In [11]:
from sklearn.utils import shuffle
df_faces = shuffle(df_faces)

In [12]:
df_faces

,0,1,2,3,4,5,6,7,8,9,...,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600
0,1,146,144,139,143,149,154,154,156,162,...,124,120,84,64,39,39,39,41,40,40
0,0,65,74,88,91,98,104,105,105,102,...,145,142,138,139,137,120,117,132,116,92
0,1,106,111,106,111,108,106,112,106,110,...,134,129,118,116,109,103,104,110,116,130
0,0,138,136,133,134,140,144,148,156,158,...,131,128,122,123,117,109,105,85,103,149
0,0,69,73,77,78,67,58,58,68,76,...,102,96,100,109,123,119,120,122,109,80
0,0,59,56,43,39,36,36,41,50,55,...,64,63,68,70,68,70,74,76,79,71
0,0,164,96,156,177,183,195,205,215,207,...,34,30,42,49,87,82,84,109,112,90
0,1,42,55,57,63,78,98,106,125,132,...,179,177,170,167,157,141,136,129,125,118
0,0,128,137,140,145,149,164,175,187,196,...,141,141,128,122,96,79,71,70,72,61
0,1,138,143,149,146,147,144,140,138,150,...,134,117,102,101,72,92,135,207,209,227
0,1,30,32,31,35,48,160,176,189,193,...,139,138,136,136,133,130,128,123,119,113
0,1,138,136,133,134,140,144,148,156,158,...,131,128,122,123,117,109,105,85,103,149

In [13]:
df_faces.to_csv('datos/img_faces_test.csv', index=False)

## Ahora se genera el dataframe de aprendizaje

In [ ]:
count = 0
df_negative = pd.DataFrame()
for imagen in glob('datos/faces_test/negatives/*.jpg'):
    img = cv.imread(imagen)
    img_gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    img_r = cv.resize(img_gray, (40,40), interpolation = cv.INTER_NEAREST)
    fila = np.append(0, img_r.flatten())
    fila = fila.reshape(1, 1601  )
    df_negative = pd.concat([df_negative,  pd.DataFrame(fila)  ])
    count = count + 1
print(count)

In [ ]:
count = 0
df_postive = pd.DataFrame()
for imagen in glob('datos/faces_test/positives/*.jpg'):
    img = cv.imread(imagen)
    img_gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    img_r = cv.resize(img_gray, (40,40), interpolation = cv.INTER_NEAREST)
    fila = np.append(1, img_r.flatten())
    fila = fila.reshape(1, 1601  )
    df_postive = pd.concat([df_postive,  pd.DataFrame(fila)  ])
    count = count + 1
print(count)